import { createThemedStyles } from '@/features/appearance/theme-provider';
import { StyleSheet } from "react-native";

export const useStyles = createThemedStyles((themeColor) => StyleSheet.create({
  page: {
    width: "100%",
    maxWidth: 1160,
    alignSelf: "center",
    paddingTop: 30,
    paddingBottom: 130,
    paddingHorizontal: 30,
  },
  pageSmall: { paddingHorizontal: 18, paddingTop: 20 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 25,
  },
  heading: { flex: 1 },
  inline: { flexDirection: "row", alignItems: "center", gap: 7 },
  flex: { flex: 1 },
  coralDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: themeColor("#F36B68", 'accentSoft'),
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "700",
    color: themeColor("#93909A", 'muted'),
  },
  title: {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: "800",
    letterSpacing: -1.8,
    color: themeColor("#24242C", 'text'),
    marginTop: 7,
  },
  subtitle: { fontSize: 14, color: themeColor("#8C8B95", 'muted'), marginTop: 3 },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    alignItems: "center",
    justifyContent: "center",
  },
  filterPanel: { gap: 10 },
  filterPanelWide: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  periods: {
    flexDirection: "row",
    backgroundColor: themeColor("#EDEDF0", 'elevated'),
    padding: 4,
    borderRadius: 13,
    gap: 2,
    minWidth: 280,
  },
  period: {
    flex: 1,
    minWidth: 55,
    height: 36,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  periodActive: {
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    boxShadow: "0 2px 5px #2323300D",
  },
  periodText: { fontSize: 12, fontWeight: "600", color: themeColor("#888793", 'muted') },
  periodTextActive: { color: themeColor("#303038", 'text') },
  customPeriod: {
    width: 42,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  dateNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  dateLabelButton: { paddingVertical: 12, flexShrink: 1 },
  dateLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: themeColor("#62616F", 'secondary'),
    textAlign: "center",
  },
  categoryFilters: { gap: 8, paddingTop: 19, paddingBottom: 20 },
  categoryPill: {
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    paddingHorizontal: 14,
    height: 42,
    borderRadius: 22,
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    borderWidth: 1,
    borderColor: themeColor("#EBEBEF", 'border'),
  },
  categoryPillText: { color: themeColor("#81808C", 'muted'), fontSize: 12, fontWeight: "600" },
  subcategoryFilters: { gap: 8, paddingBottom: 20 },
  subcategory: { paddingHorizontal: 13, paddingVertical: 11, borderRadius: 12 },
  subcategoryActive: { backgroundColor: themeColor("#EAE9F1", 'elevated') },
  subcategoryText: { fontSize: 12, color: themeColor("#8C8796", 'muted') },
  subcategoryTextActive: { color: themeColor("#5E536F", 'secondary'), fontWeight: "600" },
  dashboard: { gap: 17 },
  card: {
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    borderRadius: 25,
    padding: 23,
    borderWidth: 1,
    borderColor: themeColor("#F0F0F3", 'border'),
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  cardTitle: { fontSize: 13, fontWeight: "700", flexShrink: 1 },
  cardDescription: {
    fontSize: 12,
    color: themeColor("#92909B", 'muted'),
    marginTop: 9,
    lineHeight: 18,
  },
  gridRow: { gap: 17 },
  gridRowWide: { flexDirection: "row", alignItems: "stretch" },
  overviewWide: { flex: 0.95 },
  timelineWide: { flex: 1.25 },
  scopeBadge: {
    maxWidth: "50%",
    flexShrink: 1,
    backgroundColor: themeColor("#F7F7F9", 'surface'),
    borderRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  scopeText: {
    fontSize: 8,
    color: themeColor("#A5A1AC", 'muted'),
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  overviewBody: { paddingTop: 20 },
  heroNumber: {
    fontSize: 49,
    lineHeight: 54,
    fontWeight: "700",
    color: themeColor("#26262D", 'text'),
    letterSpacing: -2.3,
    fontVariant: ["tabular-nums"],
  },
  heroUnit: { color: themeColor("#8C8A98", 'muted'), fontSize: 12, marginTop: 1 },
  legendDot: { width: 6, height: 6, borderRadius: 3 },
  cardFootnote: {
    fontSize: 10,
    lineHeight: 16,
    color: themeColor("#89838F", 'muted'),
    marginTop: 12,
  },
  smallTag: {
    fontSize: 8,
    letterSpacing: 1,
    color: themeColor("#B0ADB6", 'muted'),
    fontWeight: "600",
  },
  chartSummary: { marginTop: 28, gap: 7 },
  chartNumber: {
    fontSize: 38,
    fontWeight: "700",
    color: themeColor("#30303A", 'text'),
    letterSpacing: -1.3,
    fontVariant: ["tabular-nums"],
  },
  chartUnit: {
    fontSize: 13,
    fontWeight: "500",
    color: themeColor("#93909B", 'muted'),
    letterSpacing: 0,
  },
  muted: { fontSize: 12, color: themeColor("#817A8B", 'muted'), lineHeight: 18 },
  smallMuted: { fontSize: 10, color: themeColor("#827C89", 'muted'), lineHeight: 16 },
  chartHint: {
    fontSize: 10,
    textAlign: "center",
    color: themeColor("#89838F", 'muted'),
    marginTop: 20,
  },
  trendRow: {
    borderTopWidth: 1,
    borderColor: themeColor("#F0EFF4", 'border'),
    marginTop: 25,
    paddingTop: 19,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  trendIcon: {
    width: 36,
    height: 36,
    backgroundColor: themeColor("#F6F5F8", 'elevated'),
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
  },
  trendTitle: {
    fontSize: 11,
    color: themeColor("#6E667B", 'muted'),
    fontWeight: "600",
    marginBottom: 3,
  },
  metricsRow: { flexDirection: "row", gap: 12 },
  metricsWide: { gap: 17 },
  metricCard: { flex: 1, padding: 17, borderRadius: 22 },
  metricNumber: {
    fontSize: 36,
    fontWeight: "700",
    marginTop: 20,
    letterSpacing: -1.4,
  },
  percentUnit: { fontSize: 22 },
  metricDescription: {
    fontSize: 10,
    lineHeight: 16,
    color: themeColor("#827C89", 'muted'),
    marginTop: 4,
    minHeight: 32,
  },
  peopleDots: { flexDirection: "row", gap: 5, marginTop: 16 },
  peopleDot: { width: 8, height: 8, borderRadius: 4 },
  progressTrack: {
    marginTop: 18,
    height: 6,
    backgroundColor: themeColor("#EAF4ED", 'successSoft'),
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: { height: 6, borderRadius: 3, backgroundColor: "#69B192" },
  community: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    borderRadius: 22,
    backgroundColor: themeColor("#FCF0E9", 'warningSoft'),
    gap: 2,
  },
  communityTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    letterSpacing: -0.5,
    color: themeColor("#795F58", 'secondary'),
  },
  communityText: {
    fontSize: 11,
    lineHeight: 18,
    color: themeColor("#B0938A", 'muted'),
    marginTop: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 13,
    marginBottom: -3,
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: "700",
    letterSpacing: -0.5,
    color: themeColor("#32303A", 'text'),
  },
  sectionSubtitle: { fontSize: 10, color: themeColor("#ABA5B3", 'muted') },
  kindList: { gap: 20, marginTop: 25 },
  kindRow: { gap: 8 },
  kindLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  kindLabel: { fontSize: 12, color: themeColor("#6B6577", 'muted') },
  kindValue: { fontSize: 12, fontWeight: "700", color: themeColor("#5C546B", 'secondary') },
  kindPercent: { fontWeight: "400", color: themeColor("#ABA5B3", 'muted'), fontSize: 11 },
  kindTrack: {
    height: 7,
    backgroundColor: themeColor("#F4F2F6", 'elevated'),
    borderRadius: 4,
    overflow: "hidden",
  },
  kindFill: { height: 7, borderRadius: 4 },
  severitySection: {
    borderTopWidth: 1,
    borderColor: themeColor("#F1EFF5", 'border'),
    paddingTop: 21,
    marginTop: 26,
  },
  severityTitle: { color: themeColor("#7A7187", 'muted'), fontSize: 12, fontWeight: "600" },
  severityItems: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginTop: 13,
  },
  severityItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: themeColor("#FAF9FB", 'surface'),
    padding: 8,
    borderRadius: 9,
  },
  severityLabel: { fontSize: 9, color: themeColor("#9A91A6", 'muted') },
  severityCount: { fontSize: 10, fontWeight: "700", color: themeColor("#73697F", 'muted') },
  sideColumn: { gap: 17 },
  hourSummary: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 10,
    marginTop: 21,
    flexWrap: "wrap",
  },
  hourNumber: {
    fontSize: 31,
    fontWeight: "700",
    color: themeColor("#7971C7", 'info'),
    letterSpacing: -1,
  },
  hourCaption: { fontSize: 10, color: themeColor("#ABA5B6", 'muted') },
  heatLegend: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 17,
  },
  heatSwatch: { width: 9, height: 9, borderRadius: 2 },
  insightCard: { backgroundColor: themeColor("#FBF7EE", 'warningSoft'), borderColor: themeColor("#F4EFE2", 'border') },
  insightIcon: { backgroundColor: themeColor("#F5EDDA", 'warningSoft'), padding: 7, borderRadius: 11 },
  insightTitle: { fontSize: 13, fontWeight: "700", color: themeColor("#978367", 'muted') },
  insightText: {
    fontSize: 13,
    lineHeight: 21,
    color: themeColor("#9E8E78", 'muted'),
    marginTop: 13,
  },
  insightBold: { fontWeight: "700", color: themeColor("#857054", 'secondary') },
  insightNote: {
    fontSize: 10,
    lineHeight: 17,
    color: themeColor("#B5A894", 'muted'),
    marginTop: 11,
  },
  feedCard: { paddingVertical: 4, paddingHorizontal: 20 },
  eventsLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    borderWidth: 1,
    borderColor: themeColor("#F1EBEE", 'border'),
    borderRadius: 22,
    paddingHorizontal: 22,
    paddingVertical: 20,
  },
  eventsLinkEyebrow: {
    color: themeColor("#E57380", 'accent'),
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  eventsLinkTitle: {
    color: themeColor("#33313A", 'text'),
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: -0.3,
    marginTop: 5,
  },
  eventsLinkSubtitle: {
    color: themeColor("#928C99", 'muted'),
    fontSize: 11,
    marginTop: 5,
  },
  eventsLinkArrow: {
    width: 39,
    height: 39,
    borderRadius: 20,
    backgroundColor: themeColor("#FDEDF0", 'accentSoft'),
    alignItems: "center",
    justifyContent: "center",
  },
  eventsContext: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    backgroundColor: themeColor("#FDEFF1", 'accentSoft'),
    borderRadius: 19,
    padding: 15,
    marginBottom: 17,
  },
  eventsContextIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    alignItems: "center",
    justifyContent: "center",
  },
  eventsContextTitle: { color: themeColor("#614C59", 'secondary'), fontSize: 13, fontWeight: "700" },
  eventsContextPeriod: { color: themeColor("#9D8992", 'muted'), fontSize: 11, marginTop: 4 },
  eventsContextCount: {
    color: themeColor("#D95F74", 'accent'),
    fontSize: 24,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  reportRow: {
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
  },
  reportBorder: { borderTopWidth: 1, borderColor: themeColor("#F3F0F5", 'border') },
  reportIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  reportTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  reportTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: themeColor("#675C74", 'secondary'),
    flexShrink: 1,
  },
  reportLocation: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    marginTop: 6,
  },
  reportPlace: { fontSize: 11, color: themeColor("#968B9F", 'muted'), flex: 1 },
  reportMeta: { fontSize: 10, color: themeColor("#B5AABA", 'muted'), marginTop: 5 },
  loadMore: {
    alignItems: "center",
    padding: 20,
    borderTopWidth: 1,
    borderColor: themeColor("#F3F0F5", 'border'),
  },
  link: { color: themeColor("#E36674", 'accent'), fontWeight: "600", fontSize: 12 },
  method: { flexDirection: "row", gap: 8, paddingHorizontal: 5, marginTop: 5 },
  methodText: { fontSize: 11, color: themeColor("#99929F", 'muted'), lineHeight: 16 },
  methodDetail: {
    fontSize: 10,
    color: themeColor("#B0A7B5", 'muted'),
    lineHeight: 17,
    marginTop: 5,
  },
  loadingArea: { alignItems: "center", paddingTop: 70, gap: 14 },
  loadingText: { color: themeColor("#A293A7", 'muted'), fontSize: 13 },
  skeletonRow: { flexDirection: "row", gap: 15, width: "100%", marginTop: 20 },
  skeleton: {
    height: 240,
    borderRadius: 24,
    backgroundColor: themeColor("#F0EEF3", 'elevated'),
    flex: 1,
  },
  empty: { alignItems: "center", paddingVertical: 50, gap: 15 },
  emptyTitle: { fontSize: 19, fontWeight: "600", color: themeColor("#74667E", 'muted') },
  emptyText: {
    textAlign: "center",
    color: themeColor("#A294AC", 'muted'),
    fontSize: 13,
    lineHeight: 21,
    maxWidth: 320,
  },
  emptyChartText: {
    color: themeColor("#B5A6BA", 'muted'),
    fontSize: 12,
    lineHeight: 20,
    paddingVertical: 30,
  },
  emptyFeed: { alignItems: "center", padding: 30, gap: 12 },
  retry: {
    backgroundColor: themeColor("#FCEBF0", 'accentSoft'),
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
  },
  retryText: { color: themeColor("#D66E80", 'accent'), fontWeight: "600" },
  noResults: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: themeColor("#EEEBF2", 'elevated'),
    borderRadius: 17,
    padding: 15,
  },
  noResultsTitle: {
    fontSize: 12,
    color: themeColor("#76677F", 'muted'),
    fontWeight: "600",
    marginBottom: 4,
  },
  resetButton: { paddingVertical: 12 },
  modalBackdrop: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: themeColor("#24212F66", 'overlay'),
  },
  backdropDismiss: { ...StyleSheet.absoluteFill },
  dateSheet: {
    width: "100%",
    maxWidth: 430,
    backgroundColor: themeColor("white", 'surface'),
    borderRadius: 28,
    padding: 25,
  },
  sheetTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: themeColor("#3E344A", 'text'),
    letterSpacing: -0.6,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: themeColor("#8A7B97", 'muted'),
    marginTop: 20,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: themeColor("#E8E0EE", 'border'),
    borderRadius: 12,
    backgroundColor: themeColor("#FCFAFD", 'surface'),
    padding: 15,
    color: themeColor("#5A486C", 'secondary'),
    fontSize: 16,
    marginBottom: 6,
  },
  applyButton: {
    backgroundColor: themeColor("#F06C7B", 'accentSoft'),
    paddingVertical: 16,
    alignItems: "center",
    borderRadius: 14,
    marginTop: 22,
  },
  applyText: { color: "white", fontSize: 14, fontWeight: "600" },
  error: { color: themeColor("#C45E73", 'accent'), fontSize: 12, lineHeight: 20, marginTop: 10 },
}));
