import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    width: "100%",
    maxWidth: 1160,
    alignSelf: "center",
    paddingTop: 30,
    paddingBottom: 130,
    paddingHorizontal: 30,
  },
  pageSmall: { paddingHorizontal: 18, paddingTop: 20 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 25,
  },
  heading: { flex: 1 },
  inline: { flexDirection: "row", alignItems: "center", gap: 7 },
  flex: { flex: 1 },
  coralDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#F36B68",
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "700",
    color: "#93909A",
  },
  title: {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: "800",
    letterSpacing: -1.8,
    color: "#24242C",
    marginTop: 7,
  },
  subtitle: { fontSize: 14, color: "#8C8B95", marginTop: 3 },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  filterPanel: { gap: 10 },
  filterPanelWide: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  periods: {
    flexDirection: "row",
    backgroundColor: "#EDEDF0",
    padding: 4,
    borderRadius: 13,
    gap: 2,
    minWidth: 280,
  },
  period: {
    flex: 1,
    minWidth: 55,
    height: 36,
    paddingHorizontal: 6,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  periodActive: {
    backgroundColor: "#FFFFFF",
    boxShadow: "0 2px 5px #2323300D",
  },
  periodText: { fontSize: 12, fontWeight: "600", color: "#888793" },
  periodTextActive: { color: "#303038" },
  customPeriod: {
    width: 42,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  dateNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  dateLabelButton: { paddingVertical: 12, flexShrink: 1 },
  dateLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#62616F",
    textAlign: "center",
  },
  categoryFilters: { gap: 8, paddingTop: 19, paddingBottom: 20 },
  categoryPill: {
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    paddingHorizontal: 14,
    height: 42,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EBEBEF",
  },
  categoryPillText: { color: "#81808C", fontSize: 12, fontWeight: "600" },
  subcategoryFilters: { gap: 8, paddingBottom: 20 },
  subcategory: { paddingHorizontal: 13, paddingVertical: 11, borderRadius: 12 },
  subcategoryActive: { backgroundColor: "#EAE9F1" },
  subcategoryText: { fontSize: 12, color: "#8C8796" },
  subcategoryTextActive: { color: "#5E536F", fontWeight: "600" },
  dashboard: { gap: 17 },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    padding: 23,
    borderWidth: 1,
    borderColor: "#F0F0F3",
  },
  cardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  cardTitle: { fontSize: 13, fontWeight: "700", flexShrink: 1 },
  cardDescription: {
    fontSize: 12,
    color: "#92909B",
    marginTop: 9,
    lineHeight: 18,
  },
  gridRow: { gap: 17 },
  gridRowWide: { flexDirection: "row", alignItems: "stretch" },
  overviewWide: { flex: 0.95 },
  timelineWide: { flex: 1.25 },
  scopeBadge: {
    maxWidth: "50%",
    flexShrink: 1,
    backgroundColor: "#F7F7F9",
    borderRadius: 6,
    paddingVertical: 5,
    paddingHorizontal: 8,
  },
  scopeText: {
    fontSize: 8,
    color: "#A5A1AC",
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  overviewBody: { paddingTop: 20 },
  heroNumber: {
    fontSize: 49,
    lineHeight: 54,
    fontWeight: "700",
    color: "#26262D",
    letterSpacing: -2.3,
    fontVariant: ["tabular-nums"],
  },
  heroUnit: { color: "#8C8A98", fontSize: 12, marginTop: 1 },
  legendDot: { width: 6, height: 6, borderRadius: 3 },
  cardFootnote: {
    fontSize: 10,
    lineHeight: 16,
    color: "#89838F",
    marginTop: 12,
  },
  smallTag: {
    fontSize: 8,
    letterSpacing: 1,
    color: "#B0ADB6",
    fontWeight: "600",
  },
  chartSummary: { marginTop: 28, gap: 7 },
  chartNumber: {
    fontSize: 38,
    fontWeight: "700",
    color: "#30303A",
    letterSpacing: -1.3,
    fontVariant: ["tabular-nums"],
  },
  chartUnit: {
    fontSize: 13,
    fontWeight: "500",
    color: "#93909B",
    letterSpacing: 0,
  },
  muted: { fontSize: 12, color: "#817A8B", lineHeight: 18 },
  smallMuted: { fontSize: 10, color: "#827C89", lineHeight: 16 },
  chartHint: {
    fontSize: 10,
    textAlign: "center",
    color: "#89838F",
    marginTop: 20,
  },
  trendRow: {
    borderTopWidth: 1,
    borderColor: "#F0EFF4",
    marginTop: 25,
    paddingTop: 19,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  trendIcon: {
    width: 36,
    height: 36,
    backgroundColor: "#F6F5F8",
    borderRadius: 11,
    justifyContent: "center",
    alignItems: "center",
  },
  trendTitle: {
    fontSize: 11,
    color: "#6E667B",
    fontWeight: "600",
    marginBottom: 3,
  },
  metricsRow: { flexDirection: "row", gap: 12 },
  metricsWide: { gap: 17 },
  metricCard: { flex: 1, padding: 17, borderRadius: 22 },
  metricNumber: {
    fontSize: 36,
    fontWeight: "700",
    marginTop: 20,
    letterSpacing: -1.4,
  },
  percentUnit: { fontSize: 22 },
  metricDescription: {
    fontSize: 10,
    lineHeight: 16,
    color: "#827C89",
    marginTop: 4,
    minHeight: 32,
  },
  peopleDots: { flexDirection: "row", gap: 5, marginTop: 16 },
  peopleDot: { width: 8, height: 8, borderRadius: 4 },
  progressTrack: {
    marginTop: 18,
    height: 6,
    backgroundColor: "#EAF4ED",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: { height: 6, borderRadius: 3, backgroundColor: "#69B192" },
  community: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    borderRadius: 22,
    backgroundColor: "#FCF0E9",
    gap: 2,
  },
  communityTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    letterSpacing: -0.5,
    color: "#795F58",
  },
  communityText: {
    fontSize: 11,
    lineHeight: 18,
    color: "#B0938A",
    marginTop: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 13,
    marginBottom: -3,
  },
  sectionTitle: {
    fontSize: 21,
    fontWeight: "700",
    letterSpacing: -0.5,
    color: "#32303A",
  },
  sectionSubtitle: { fontSize: 10, color: "#ABA5B3" },
  kindList: { gap: 20, marginTop: 25 },
  kindRow: { gap: 8 },
  kindLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  kindLabel: { fontSize: 12, color: "#6B6577" },
  kindValue: { fontSize: 12, fontWeight: "700", color: "#5C546B" },
  kindPercent: { fontWeight: "400", color: "#ABA5B3", fontSize: 11 },
  kindTrack: {
    height: 7,
    backgroundColor: "#F4F2F6",
    borderRadius: 4,
    overflow: "hidden",
  },
  kindFill: { height: 7, borderRadius: 4 },
  severitySection: {
    borderTopWidth: 1,
    borderColor: "#F1EFF5",
    paddingTop: 21,
    marginTop: 26,
  },
  severityTitle: { color: "#7A7187", fontSize: 12, fontWeight: "600" },
  severityItems: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginTop: 13,
  },
  severityItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#FAF9FB",
    padding: 8,
    borderRadius: 9,
  },
  severityLabel: { fontSize: 9, color: "#9A91A6" },
  severityCount: { fontSize: 10, fontWeight: "700", color: "#73697F" },
  sideColumn: { gap: 17 },
  hourSummary: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 10,
    marginTop: 21,
    flexWrap: "wrap",
  },
  hourNumber: {
    fontSize: 31,
    fontWeight: "700",
    color: "#7971C7",
    letterSpacing: -1,
  },
  hourCaption: { fontSize: 10, color: "#ABA5B6" },
  heatLegend: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 17,
  },
  heatSwatch: { width: 9, height: 9, borderRadius: 2 },
  insightCard: { backgroundColor: "#FBF7EE", borderColor: "#F4EFE2" },
  insightIcon: { backgroundColor: "#F5EDDA", padding: 7, borderRadius: 11 },
  insightTitle: { fontSize: 13, fontWeight: "700", color: "#978367" },
  insightText: {
    fontSize: 13,
    lineHeight: 21,
    color: "#9E8E78",
    marginTop: 13,
  },
  insightBold: { fontWeight: "700", color: "#857054" },
  insightNote: {
    fontSize: 10,
    lineHeight: 17,
    color: "#B5A894",
    marginTop: 11,
  },
  feedCard: { paddingVertical: 4, paddingHorizontal: 20 },
  eventsLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F1EBEE",
    borderRadius: 22,
    paddingHorizontal: 22,
    paddingVertical: 20,
  },
  eventsLinkEyebrow: {
    color: "#E57380",
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  eventsLinkTitle: {
    color: "#33313A",
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: -0.3,
    marginTop: 5,
  },
  eventsLinkSubtitle: {
    color: "#928C99",
    fontSize: 11,
    marginTop: 5,
  },
  eventsLinkArrow: {
    width: 39,
    height: 39,
    borderRadius: 20,
    backgroundColor: "#FDEDF0",
    alignItems: "center",
    justifyContent: "center",
  },
  eventsContext: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    backgroundColor: "#FDEFF1",
    borderRadius: 19,
    padding: 15,
    marginBottom: 17,
  },
  eventsContextIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  eventsContextTitle: { color: "#614C59", fontSize: 13, fontWeight: "700" },
  eventsContextPeriod: { color: "#9D8992", fontSize: 11, marginTop: 4 },
  eventsContextCount: {
    color: "#D95F74",
    fontSize: 24,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },
  reportRow: {
    paddingVertical: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
  },
  reportBorder: { borderTopWidth: 1, borderColor: "#F3F0F5" },
  reportIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  reportTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  reportTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#675C74",
    flexShrink: 1,
  },
  reportLocation: {
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    marginTop: 6,
  },
  reportPlace: { fontSize: 11, color: "#968B9F", flex: 1 },
  reportMeta: { fontSize: 10, color: "#B5AABA", marginTop: 5 },
  loadMore: {
    alignItems: "center",
    padding: 20,
    borderTopWidth: 1,
    borderColor: "#F3F0F5",
  },
  link: { color: "#E36674", fontWeight: "600", fontSize: 12 },
  method: { flexDirection: "row", gap: 8, paddingHorizontal: 5, marginTop: 5 },
  methodText: { fontSize: 11, color: "#99929F", lineHeight: 16 },
  methodDetail: {
    fontSize: 10,
    color: "#B0A7B5",
    lineHeight: 17,
    marginTop: 5,
  },
  loadingArea: { alignItems: "center", paddingTop: 70, gap: 14 },
  loadingText: { color: "#A293A7", fontSize: 13 },
  skeletonRow: { flexDirection: "row", gap: 15, width: "100%", marginTop: 20 },
  skeleton: {
    height: 240,
    borderRadius: 24,
    backgroundColor: "#F0EEF3",
    flex: 1,
  },
  empty: { alignItems: "center", paddingVertical: 50, gap: 15 },
  emptyTitle: { fontSize: 19, fontWeight: "600", color: "#74667E" },
  emptyText: {
    textAlign: "center",
    color: "#A294AC",
    fontSize: 13,
    lineHeight: 21,
    maxWidth: 320,
  },
  emptyChartText: {
    color: "#B5A6BA",
    fontSize: 12,
    lineHeight: 20,
    paddingVertical: 30,
  },
  emptyFeed: { alignItems: "center", padding: 30, gap: 12 },
  retry: {
    backgroundColor: "#FCEBF0",
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
  },
  retryText: { color: "#D66E80", fontWeight: "600" },
  noResults: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#EEEBF2",
    borderRadius: 17,
    padding: 15,
  },
  noResultsTitle: {
    fontSize: 12,
    color: "#76677F",
    fontWeight: "600",
    marginBottom: 4,
  },
  resetButton: { paddingVertical: 12 },
  modalBackdrop: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#24212F66",
  },
  backdropDismiss: { ...StyleSheet.absoluteFill },
  dateSheet: {
    width: "100%",
    maxWidth: 430,
    backgroundColor: "white",
    borderRadius: 28,
    padding: 25,
  },
  sheetTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#3E344A",
    letterSpacing: -0.6,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#8A7B97",
    marginTop: 20,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: "#E8E0EE",
    borderRadius: 12,
    backgroundColor: "#FCFAFD",
    padding: 15,
    color: "#5A486C",
    fontSize: 16,
    marginBottom: 6,
  },
  applyButton: {
    backgroundColor: "#F06C7B",
    paddingVertical: 16,
    alignItems: "center",
    borderRadius: 14,
    marginTop: 22,
  },
  applyText: { color: "white", fontSize: 14, fontWeight: "600" },
  error: { color: "#C45E73", fontSize: 12, lineHeight: 20, marginTop: 10 },
});
