import { createThemedStyles } from '@/features/appearance/theme-provider';
import { StyleSheet } from "react-native";

export const useStyles = createThemedStyles((themeColor) => StyleSheet.create({
  grow: { flex: 1, minWidth: 0 },
  sections: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    gap: 30,
    marginTop: 34,
  },
  section: { gap: 13 },
  sectionHeading: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 36,
    gap: 8,
  },
  headingLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
  },
  sectionNumber: {
    color: themeColor("#879283", 'muted'),
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 1,
  },
  sectionTitle: {
    color: themeColor("#29392F", 'text'),
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "700",
    letterSpacing: -0.65,
  },
  textAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minHeight: 44,
    paddingLeft: 8,
  },
  textActionLabel: { color: themeColor("#3D574C", 'secondary'), fontSize: 12, fontWeight: "600" },
  nearbyCard: {
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    borderRadius: 25,
    borderWidth: 1,
    borderColor: themeColor("#E7EAE1", 'border'),
    overflow: "hidden",
  },
  nearbyTop: { padding: 20, paddingBottom: 15, gap: 7 },
  nearbyCaption: { flexDirection: "row", alignItems: "center", gap: 7 },
  smallDot: {
    width: 6,
    height: 6,
    backgroundColor: "#718C61",
    borderRadius: 3,
  },
  areaLabel: {
    color: themeColor("#3D5845", 'secondary'),
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 1,
  },
  periodLabel: {
    fontSize: 10,
    letterSpacing: 1.5,
    color: themeColor("#687365", 'secondary'),
    marginLeft: 13,
  },
  radiusRow: {
    marginHorizontal: 18,
    paddingBottom: 14,
    gap: 9,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  radiusLabel: { fontSize: 11, color: themeColor("#727F73", 'muted') },
  radiusOptions: { flexDirection: "row", gap: 5 },
  radiusOption: {
    paddingHorizontal: 13,
    minHeight: 40,
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: themeColor("#F4F5F0", 'elevated'),
  },
  radiusSelected: { backgroundColor: "#315342" },
  radiusText: { fontSize: 11, color: themeColor("#697768", 'muted'), fontWeight: "600" },
  radiusTextSelected: { color: "#FFFFFF" },
  locationPrompt: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    backgroundColor: themeColor("#F1F4EA", 'successSoft'),
    padding: 14,
    marginHorizontal: 17,
    borderRadius: 14,
    marginBottom: 9,
  },
  locationPromptText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: themeColor("#4F654E", 'secondary'),
  },
  locationError: {
    color: themeColor("#9A574B", 'accent'),
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  reportRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    paddingHorizontal: 18,
    paddingVertical: 19,
    borderTopColor: themeColor("#F0F1EB", 'border'),
    borderTopWidth: 1,
  },
  reportIcon: {
    width: 43,
    height: 47,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  reportTitle: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "600",
    color: themeColor("#303B33", 'text'),
  },
  reportLocation: {
    fontSize: 12,
    lineHeight: 18,
    color: themeColor("#6F786F", 'muted'),
    marginTop: 3,
  },
  reportMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
    marginTop: 6,
  },
  metaText: { fontSize: 10, color: themeColor("#667261", 'secondary') },
  metaDot: { width: 3, height: 3, borderRadius: 2, backgroundColor: themeColor("#A9B0A4", 'elevated') },
  feedFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: themeColor("#FAFBF7", 'surface'),
    borderTopWidth: 1,
    borderTopColor: themeColor("#F0F1EB", 'border'),
    paddingLeft: 19,
    paddingRight: 6,
  },
  feedFooterText: { color: themeColor("#66735F", 'secondary'), fontSize: 10, flex: 1 },
  refresh: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  empty: {
    paddingVertical: 28,
    paddingHorizontal: 22,
    gap: 10,
    alignItems: "center",
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: themeColor("#F2F5EC", 'successSoft'),
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    color: themeColor("#3E5544", 'secondary'),
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyBody: {
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    color: themeColor("#63705D", 'secondary'),
    maxWidth: 330,
  },
  body: { color: themeColor("#63705D", 'secondary'), fontSize: 13, lineHeight: 20 },
  dataNote: {
    color: themeColor("#706D61", 'secondary'),
    fontSize: 11,
    lineHeight: 17,
    marginHorizontal: 19,
    marginVertical: 12,
  },
  inlineButton: {
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  linkLabel: { color: themeColor("#355447", 'secondary'), fontWeight: "700", fontSize: 12 },
  journeyCard: {
    borderRadius: 27,
    backgroundColor: "#203F35",
    overflow: "hidden",
    padding: 23,
  },
  journeyTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  journeyTag: { flexDirection: "row", alignItems: "center", gap: 7 },
  journeyEyebrow: {
    fontSize: 10,
    letterSpacing: 1.3,
    color: "#C6DCC1",
    fontWeight: "500",
  },
  journeyCompass: {
    width: 30,
    height: 30,
    borderWidth: 1,
    borderColor: "#496456",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  journeyTitle: {
    color: "#F6F4E9",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "600",
    letterSpacing: -1,
    marginTop: 14,
  },
  journeyDescription: {
    color: "#AEBCAB",
    fontSize: 13,
    lineHeight: 20,
    maxWidth: 300,
    marginTop: 11,
  },
  journeyArt: {
    marginHorizontal: -23,
    marginTop: 1,
    marginBottom: -2,
    height: 110,
    overflow: "hidden",
  },
  savedRoutes: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2C4A3F",
    borderWidth: 1,
    borderColor: "#3E5A49",
    borderRadius: 15,
    paddingVertical: 5,
  },
  savedRoute: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 12,
    minHeight: 65,
  },
  savedRouteTitle: { fontSize: 12, color: "#EAF0E3", fontWeight: "600" },
  savedRouteAddress: { fontSize: 10, color: "#ADBEA9", marginTop: 5 },
  routeDivider: { height: 28, width: 1, backgroundColor: "#536A55" },
  journeyError: {
    fontSize: 11,
    lineHeight: 17,
    color: "#E7C6B3",
    marginTop: 10,
  },
  journeyCta: {
    marginTop: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 8,
    paddingLeft: 17,
    borderRadius: 15,
    backgroundColor: "#D4E9C5",
    gap: 8,
    minHeight: 54,
  },
  journeyCtaText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#254632",
    flex: 1,
  },
  ctaArrow: {
    width: 35,
    height: 35,
    borderRadius: 11,
    backgroundColor: "#E3F0D8",
    alignItems: "center",
    justifyContent: "center",
  },
  otherRoute: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 44,
    marginBottom: -9,
  },
  otherRouteText: { fontSize: 11, color: "#D3E0D3" },
  zonesCard: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 24,
    backgroundColor: themeColor("#ECEFE3", 'successSoft'),
    borderWidth: 1,
    borderColor: themeColor("#E2E7D7", 'border'),
    padding: 22,
    gap: 5,
  },
  eyebrowLine: { flexDirection: "row", gap: 6, alignItems: "center" },
  softEyebrow: {
    fontSize: 10,
    letterSpacing: 1.6,
    color: themeColor("#66785E", 'secondary'),
    fontWeight: "700",
  },
  zonesTitle: {
    fontSize: 23,
    fontWeight: "600",
    lineHeight: 28,
    letterSpacing: -0.6,
    color: themeColor("#344932", 'text'),
    marginTop: 12,
  },
  zonesBody: { color: themeColor("#5F7054", 'secondary'), fontSize: 11, lineHeight: 18, marginTop: 8 },
  zonesLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 19,
  },
  radar: { marginRight: -5, flexShrink: 0 },
  tipCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    backgroundColor: themeColor("#F6ECE3", 'warningSoft'),
    borderWidth: 1,
    borderColor: themeColor("#EDDFD2", 'border'),
    borderRadius: 21,
    padding: 19,
  },
  bookIcon: {
    width: 42,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: themeColor("#EEDBCC", 'warningSoft'),
  },
  tipEyebrow: {
    color: themeColor("#8E5E47", 'accent'),
    fontSize: 10,
    letterSpacing: 1.5,
    fontWeight: "700",
  },
  tipTitle: {
    color: themeColor("#5E473A", 'secondary'),
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    marginTop: 5,
  },
  tipDescription: {
    color: themeColor("#806856", 'secondary'),
    fontSize: 10,
    lineHeight: 16,
    marginTop: 3,
  },
  signature: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 3,
    paddingHorizontal: 25,
  },
  signatureLine: {
    height: 1,
    flex: 1,
    backgroundColor: themeColor("#DCE2D5", 'elevated'),
    maxWidth: 40,
  },
  signatureText: { fontSize: 10, letterSpacing: 1.4, color: themeColor("#88937F", 'muted') },
  modalBackdrop: {
    flex: 1,
    backgroundColor: themeColor("rgba(20, 35, 28, 0.45)", 'overlay'),
    justifyContent: "flex-end",
    alignItems: "center",
  },
  sheet: {
    backgroundColor: themeColor("#F8F9F4", 'elevated'),
    width: "100%",
    maxWidth: 620,
    maxHeight: "90%",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    boxShadow: "0 -10px 60px rgba(18,38,25,0.1)",
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: themeColor("#D4DBCE", 'elevated'),
    alignSelf: "center",
    marginTop: 11,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 24,
    paddingBottom: 16,
  },
  sheetTitle: {
    fontSize: 25,
    lineHeight: 32,
    color: themeColor("#294532", 'text'),
    fontWeight: "600",
    letterSpacing: -0.7,
    marginTop: 7,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: themeColor("#EAEFE3", 'successSoft'),
    alignItems: "center",
    justifyContent: "center",
  },
  sheetContent: { padding: 22, paddingTop: 0, gap: 16 },
  sheetDescription: { color: themeColor("#7A8474", 'muted'), fontSize: 13, lineHeight: 21 },
  zoneTabs: { flexDirection: "row", gap: 6 },
  zoneTab: {
    flex: 1,
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    backgroundColor: themeColor("#EAEFE2", 'successSoft'),
    borderRadius: 15,
  },
  zoneTabSelected: { backgroundColor: "#355543" },
  zoneTabText: { color: themeColor("#637466", 'secondary'), fontSize: 11, fontWeight: "600" },
  zoneTabTextSelected: { color: "#FFFFFF" },
  zoneContext: { flexDirection: "row", alignItems: "center", gap: 6 },
  zoneContextText: { color: themeColor("#697B6A", 'muted'), fontSize: 12, lineHeight: 19, flex: 1 },
  sheetReports: {
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: themeColor("#FFFFFF", 'surface'),
    borderWidth: 1,
    borderColor: themeColor("#E5EBDF", 'border'),
  },
  zoneEmpty: { paddingVertical: 23, gap: 15, alignItems: "center" },
  solidButton: {
    minHeight: 48,
    backgroundColor: "#355543",
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    gap: 12,
    marginTop: 5,
  },
  solidButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
  guideItem: {
    backgroundColor: themeColor("#F1E9DF", 'warningSoft'),
    padding: 23,
    borderRadius: 20,
    gap: 12,
  },
  guideTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  guideNumber: { fontSize: 25, color: themeColor("#BA9478", 'warning'), fontWeight: "300" },
  guideTitle: {
    color: themeColor("#574537", 'secondary'),
    fontSize: 19,
    lineHeight: 26,
    fontWeight: "600",
    letterSpacing: -0.5,
  },
  guideBody: { color: themeColor("#837465", 'muted'), fontSize: 13, lineHeight: 22 },
}));
