import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  grow: { flex: 1, minWidth: 0 },
  masthead: { flex: 1, paddingTop: 4, paddingBottom: 18 },
  brandLine: { flexDirection: "row", gap: 7, alignItems: "center" },
  brandMark: {
    width: 8,
    height: 8,
    borderRadius: 3,
    backgroundColor: "#F47155",
    transform: [{ rotate: "45deg" }],
  },
  brand: {
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: "800",
    color: "#5C6A60",
  },
  greeting: {
    fontSize: 19,
    lineHeight: 25,
    fontWeight: "700",
    color: "#273F32",
    letterSpacing: -0.65,
    marginTop: 9,
    maxWidth: 285,
  },
  sections: {
    width: "100%",
    maxWidth: 640,
    alignSelf: "center",
    gap: 30,
    marginTop: 34,
  },
  section: { gap: 13 },
  sectionHeading: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    minHeight: 36,
    gap: 8,
  },
  headingLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexShrink: 1,
  },
  sectionNumber: {
    color: "#879283",
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 1,
  },
  sectionTitle: {
    color: "#29392F",
    fontSize: 21,
    lineHeight: 27,
    fontWeight: "700",
    letterSpacing: -0.65,
  },
  textAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minHeight: 44,
    paddingLeft: 8,
  },
  textActionLabel: { color: "#3D574C", fontSize: 12, fontWeight: "600" },
  nearbyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#E7EAE1",
    overflow: "hidden",
  },
  nearbyTop: { padding: 20, paddingBottom: 15, gap: 7 },
  nearbyCaption: { flexDirection: "row", alignItems: "center", gap: 7 },
  smallDot: {
    width: 6,
    height: 6,
    backgroundColor: "#718C61",
    borderRadius: 3,
  },
  areaLabel: {
    color: "#3D5845",
    fontSize: 14,
    fontWeight: "600",
    flexShrink: 1,
  },
  periodLabel: {
    fontSize: 10,
    letterSpacing: 1.5,
    color: "#687365",
    marginLeft: 13,
  },
  radiusRow: {
    marginHorizontal: 18,
    paddingBottom: 14,
    gap: 9,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  radiusLabel: { fontSize: 11, color: "#727F73" },
  radiusOptions: { flexDirection: "row", gap: 5 },
  radiusOption: {
    paddingHorizontal: 13,
    minHeight: 40,
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "#F4F5F0",
  },
  radiusSelected: { backgroundColor: "#315342" },
  radiusText: { fontSize: 11, color: "#697768", fontWeight: "600" },
  radiusTextSelected: { color: "#FFFFFF" },
  locationPrompt: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    backgroundColor: "#F1F4EA",
    padding: 14,
    marginHorizontal: 17,
    borderRadius: 14,
    marginBottom: 9,
  },
  locationPromptText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: "#4F654E",
  },
  locationError: {
    color: "#9A574B",
    fontSize: 12,
    lineHeight: 18,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  reportRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    paddingHorizontal: 18,
    paddingVertical: 19,
    borderTopColor: "#F0F1EB",
    borderTopWidth: 1,
  },
  reportIcon: {
    width: 43,
    height: 47,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  reportTitle: {
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "600",
    color: "#303B33",
  },
  reportLocation: {
    fontSize: 12,
    lineHeight: 18,
    color: "#6F786F",
    marginTop: 3,
  },
  reportMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    alignItems: "center",
    marginTop: 6,
  },
  metaText: { fontSize: 10, color: "#667261" },
  metaDot: { width: 3, height: 3, borderRadius: 2, backgroundColor: "#A9B0A4" },
  feedFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FAFBF7",
    borderTopWidth: 1,
    borderTopColor: "#F0F1EB",
    paddingLeft: 19,
    paddingRight: 6,
  },
  feedFooterText: { color: "#66735F", fontSize: 10, flex: 1 },
  refresh: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  empty: {
    paddingVertical: 28,
    paddingHorizontal: 22,
    gap: 10,
    alignItems: "center",
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F2F5EC",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: {
    color: "#3E5544",
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "600",
    textAlign: "center",
  },
  emptyBody: {
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
    color: "#63705D",
    maxWidth: 330,
  },
  body: { color: "#63705D", fontSize: 13, lineHeight: 20 },
  dataNote: {
    color: "#706D61",
    fontSize: 11,
    lineHeight: 17,
    marginHorizontal: 19,
    marginVertical: 12,
  },
  inlineButton: {
    flexDirection: "row",
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
  },
  linkLabel: { color: "#355447", fontWeight: "700", fontSize: 12 },
  journeyCard: {
    borderRadius: 27,
    backgroundColor: "#203F35",
    overflow: "hidden",
    padding: 23,
  },
  journeyTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  journeyTag: { flexDirection: "row", alignItems: "center", gap: 7 },
  journeyEyebrow: {
    fontSize: 10,
    letterSpacing: 1.3,
    color: "#C6DCC1",
    fontWeight: "500",
  },
  journeyCompass: {
    width: 30,
    height: 30,
    borderWidth: 1,
    borderColor: "#496456",
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  journeyTitle: {
    color: "#F6F4E9",
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "600",
    letterSpacing: -1,
    marginTop: 14,
  },
  journeyDescription: {
    color: "#AEBCAB",
    fontSize: 13,
    lineHeight: 20,
    maxWidth: 300,
    marginTop: 11,
  },
  journeyArt: {
    marginHorizontal: -23,
    marginTop: 1,
    marginBottom: -2,
    height: 110,
    overflow: "hidden",
  },
  savedRoutes: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2C4A3F",
    borderWidth: 1,
    borderColor: "#3E5A49",
    borderRadius: 15,
    paddingVertical: 5,
  },
  savedRoute: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    padding: 12,
    minHeight: 65,
  },
  savedRouteTitle: { fontSize: 12, color: "#EAF0E3", fontWeight: "600" },
  savedRouteAddress: { fontSize: 10, color: "#ADBEA9", marginTop: 5 },
  routeDivider: { height: 28, width: 1, backgroundColor: "#536A55" },
  journeyError: {
    fontSize: 11,
    lineHeight: 17,
    color: "#E7C6B3",
    marginTop: 10,
  },
  journeyCta: {
    marginTop: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 8,
    paddingLeft: 17,
    borderRadius: 15,
    backgroundColor: "#D4E9C5",
    gap: 8,
    minHeight: 54,
  },
  journeyCtaText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#254632",
    flex: 1,
  },
  ctaArrow: {
    width: 35,
    height: 35,
    borderRadius: 11,
    backgroundColor: "#E3F0D8",
    alignItems: "center",
    justifyContent: "center",
  },
  otherRoute: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 44,
    marginBottom: -9,
  },
  otherRouteText: { fontSize: 11, color: "#D3E0D3" },
  zonesCard: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 24,
    backgroundColor: "#ECEFE3",
    borderWidth: 1,
    borderColor: "#E2E7D7",
    padding: 22,
    gap: 5,
  },
  eyebrowLine: { flexDirection: "row", gap: 6, alignItems: "center" },
  softEyebrow: {
    fontSize: 10,
    letterSpacing: 1.6,
    color: "#66785E",
    fontWeight: "700",
  },
  zonesTitle: {
    fontSize: 23,
    fontWeight: "600",
    lineHeight: 28,
    letterSpacing: -0.6,
    color: "#344932",
    marginTop: 12,
  },
  zonesBody: { color: "#5F7054", fontSize: 11, lineHeight: 18, marginTop: 8 },
  zonesLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 19,
  },
  radar: { marginRight: -5, flexShrink: 0 },
  tipCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
    backgroundColor: "#F6ECE3",
    borderWidth: 1,
    borderColor: "#EDDFD2",
    borderRadius: 21,
    padding: 19,
  },
  bookIcon: {
    width: 42,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: "#EEDBCC",
  },
  tipEyebrow: {
    color: "#8E5E47",
    fontSize: 10,
    letterSpacing: 1.5,
    fontWeight: "700",
  },
  tipTitle: {
    color: "#5E473A",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
    marginTop: 5,
  },
  tipDescription: {
    color: "#806856",
    fontSize: 10,
    lineHeight: 16,
    marginTop: 3,
  },
  signature: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 3,
    paddingHorizontal: 25,
  },
  signatureLine: {
    height: 1,
    flex: 1,
    backgroundColor: "#DCE2D5",
    maxWidth: 40,
  },
  signatureText: { fontSize: 10, letterSpacing: 1.4, color: "#88937F" },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(20, 35, 28, 0.45)",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  sheet: {
    backgroundColor: "#F8F9F4",
    width: "100%",
    maxWidth: 620,
    maxHeight: "90%",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    boxShadow: "0 -10px 60px rgba(18,38,25,0.1)",
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D4DBCE",
    alignSelf: "center",
    marginTop: 11,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 24,
    paddingBottom: 16,
  },
  sheetTitle: {
    fontSize: 25,
    lineHeight: 32,
    color: "#294532",
    fontWeight: "600",
    letterSpacing: -0.7,
    marginTop: 7,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#EAEFE3",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetContent: { padding: 22, paddingTop: 0, gap: 16 },
  sheetDescription: { color: "#7A8474", fontSize: 13, lineHeight: 21 },
  zoneTabs: { flexDirection: "row", gap: 6 },
  zoneTab: {
    flex: 1,
    gap: 7,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    backgroundColor: "#EAEFE2",
    borderRadius: 15,
  },
  zoneTabSelected: { backgroundColor: "#355543" },
  zoneTabText: { color: "#637466", fontSize: 11, fontWeight: "600" },
  zoneTabTextSelected: { color: "#FFFFFF" },
  zoneContext: { flexDirection: "row", alignItems: "center", gap: 6 },
  zoneContextText: { color: "#697B6A", fontSize: 12, lineHeight: 19, flex: 1 },
  sheetReports: {
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5EBDF",
  },
  zoneEmpty: { paddingVertical: 23, gap: 15, alignItems: "center" },
  solidButton: {
    minHeight: 48,
    backgroundColor: "#355543",
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    gap: 12,
    marginTop: 5,
  },
  solidButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "600" },
  guideItem: {
    backgroundColor: "#F1E9DF",
    padding: 23,
    borderRadius: 20,
    gap: 12,
  },
  guideTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  guideNumber: { fontSize: 25, color: "#BA9478", fontWeight: "300" },
  guideTitle: {
    color: "#574537",
    fontSize: 19,
    lineHeight: 26,
    fontWeight: "600",
    letterSpacing: -0.5,
  },
  guideBody: { color: "#837465", fontSize: 13, lineHeight: 22 },
});
